migrate from old_api
monodelic/Taskmanager pull request #15
Opened 2019-04-03 13:40 UTC by monodelic

2019-04-03 14:31 UTC, artempartos requested changes

2019-04-03 14:31 UTC, artempartos commented on app/controllers/api/application_controller.rb
> +  require 'application_responder'
это ненормально, почитай что эта инстуркциия сделает

2019-04-03 14:31 UTC, artempartos commented on app/serializers/task_serializer.rb
> +  def id
пустую строку надо добавить

2019-04-04 09:22 UTC, monodelic commented on app/serializers/task_serializer.rb
> +  def id
✔️

2019-04-04 09:33 UTC, monodelic commented on app/controllers/api/application_controller.rb
> +  require 'application_responder'
✔️

2019-04-04 13:00 UTC, artempartos commented
👍

2019-04-04 13:06 UTC, merged