model_generation added
monodelic/Taskmanager pull request #5
Opened 2019-03-11 14:03 UTC by monodelic

2019-03-18 11:59 UTC, artempartos requested changes

2019-03-18 11:59 UTC, artempartos commented on test/models/manager_test.rb
> +  # test "the truth" do
удали ненужные тесты моделей

2019-03-18 11:59 UTC, artempartos commented on test/fixtures/tasks.yml
> +  name: MyString
удали фикстуры, настрой чтобы они не создавались

2019-03-20 06:47 UTC, monodelic commented on test/models/manager_test.rb
> +  # test "the truth" do
сделано

2019-03-20 06:53 UTC, monodelic commented on test/fixtures/tasks.yml
> +  name: MyString
сделано

2019-03-20 09:15 UTC, merged

2019-03-20 12:28 UTC, artempartos commented
Ты смержил до того, как я поставил аппув
Без пальца вверх нельзя мержить