belongs and validations
monodelic/Taskmanager pull request #6
Opened 2019-03-11 14:54 UTC by monodelic

2019-03-20 12:29 UTC, artempartos commented
надо решить конфлиеты, сделай ребейз от девелопа
Научись делать ребейз

2019-03-20 12:59 UTC, artempartos requested changes

2019-03-20 12:59 UTC, artempartos commented on app/models/task.rb
> +	state_machine :initial => :new do
сделай форматирование

2019-03-21 08:05 UTC, monodelic commented on app/models/task.rb
> +	state_machine :initial => :new do
сделано

2019-03-24 20:26 UTC, artempartos commented
👍

2019-03-26 12:19 UTC, merged